<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExpertiseSeeder extends Seeder
{
    public function run(): void
    {
        $areasOfExpertise = [
            1 => 'Graphic Designer',
            2 => 'Web Designer',
            3 => 'UI/UX Designer',
            4 => 'Logo Designer',
            5 => 'Illustrator',
            6 => 'Branding Specialist',
            7 => 'Print Designer',
            8 => 'Motion Graphics Designer',
            9 => 'Video Editor',
            10 => 'Animator',
            11 => 'Photographer',
            12 => 'Copywriter',
            13 => 'Content Writer',
            14 => 'Blogger',
            15 => 'Technical Writer',
            16 => 'Editor & Proofreader',
            17 => 'Social Media Manager',
            18 => 'Social Media Marketer',
            19 => 'SEO Specialist',
            20 => 'SEM Specialist',
            21 => 'Web Developer',
            22 => 'Frontend Developer',
            23 => 'Backend Developer',
            24 => 'Full-stack Developer',
            25 => 'Mobile App Developer (iOS/Android)',
            26 => 'Game Developer',
            27 => 'Software Developer',
            28 => 'Database Manager',
            29 => 'Data Entry Specialist',
            30 => 'Data Analyst',
            31 => 'Market Researcher',
            32 => 'Business Developer',
            33 => 'Sales & Marketing Specialist',
            34 => 'Lead Generator',
            35 => 'Customer Service Representative',
            36 => 'Virtual Assistant',
            37 => 'Project Manager',
            38 => 'Product Manager',
            39 => 'Accountant & Bookkeeper',
            40 => 'Financial Analyst',
            41 => 'Legal Consultant',
            42 => 'Human Resources Specialist',
            43 => 'Translator & Localizer',
            44 => 'Transcriptionist',
            45 => 'Voice-over Artist',
            46 => 'Tutor & Teacher',
            47 => 'Online Course Creator',
            48 => 'E-learning Developer',
            49 => 'IT Support Specialist',
            50 => 'Network Administrator',
            51 => '3D Modeler',
            52 => 'CAD Designer',
            53 => 'Interior Designer',
            54 => 'Architect',
            55 => 'Landscape Designer',
            56 => 'Fashion Designer',
            57 => 'Pattern Maker',
            58 => 'Seamstress & Tailor',
            59 => 'Jewelry Designer',
            60 => 'Illustrator & Drawer',
            61 => 'Comic Book Artist',
            62 => 'Storyboard Artist',
            63 => 'Character Designer',
            64 => 'Concept Artist',
            65 => 'Scriptwriter',
            66 => 'Screenwriter',
            67 => 'Editor & Proofreader',
            68 => 'Technical Writer',
            69 => 'Grant Writer',
            70 => 'Resume Writer',
            71 => 'Cover Letter Writer',
            72 => 'Ghostwriter',
            73 => 'Fiction Writer',
            74 => 'Non-fiction Writer',
            75 => 'Article Writer',
            76 => 'Press Release Writer',
            77 => 'Speech Writer',
            78 => 'Public Relations Specialist (PR)',
            79 => 'Event Planner',
            80 => 'Event Manager',
            81 => 'Event Coordinator',
            82 => 'Wedding Planner',
            83 => 'Travel Planner',
            84 => 'Tour Guide',
            85 => 'Language Teacher',
            86 => 'Music Composer',
            87 => 'Audio Producer',
            88 => 'Sound Designer',
            89 => 'Voice Actor',
            90 => 'Podcaster',
            91 => 'Virtual Event Host',
            92 => 'Video Producer',
            93 => 'Cinematographer',
            94 => 'Script Supervisor',
            95 => 'VFX Artist',
            96 => 'Game Designer',
            97 => 'Game Tester',
            98 => 'Game Artist',
            99 => "Game Soundtrack Composer",
            100 => "Game Writer"
        ];
        foreach ($areasOfExpertise as $id => $name) {
            DB::table('expertises')->insert([
                'id' => $id,
                'expertise' => $name,
            ]);
        }
    }
}
